input:
  live_feed: True
  root: '/media/fohara/645E941F5E93E856/bme/data/'
  default: '20231124_163447.bag'

project:
  display_window: True
  lcd_monitor: False
  enable_adam_signals: False

video:
  clip_limit: 3.5
  img_height: 480
  img_width: 640
  img_wide_fov_deg: 42

parameters:
  seated_trigger: 0.75
  ui_state: 1

tracker:
  type: 'CSRT'
  bbox_height: 150
  bbox_width: 200
  bbox_qmin: 15
  
model:
  name: 'yolov4-tiny'
  cat_num: 80
  person_label: 0
  letter_box: True
  conf_thr: 0.3

serial: # sudo chmod a+rw /dev/ttyUSB0
  baud_rate: 9600
  lcd_port: '/dev/ttyUSB0'
  adam_port: '/dev/ttyACM0'

output:
  log_output: False
  output_root: '/home/fohara/project/adapt-patient-tracker/logs/'


