device: 'cuda:0'

input:
  live: True
  root:     '/media/fohara/645E941F5E93E856/bme/data/'
  select: 'example1'
  example1: '20231124_164148.bag'
  example2: '20231201_152820.bag'
  example3: '20231201_152420.bag'
  example4: '20231124_164709.bag'
  example5: '20231124_164148.bag'

processing:
  clip_limit: 4
  clip_replace: 153
  img_height: 480
  img_width: 640

tracker:
  type: 'MIL'
  bbox_height: 150
  bbox_width: 200
  distance_trigger: 0.75
