input:
  live: False
  root: '/media/fohara/645E941F5E93E856/bme/data/'
  select: None
  example1: '20231027_140116.bag'
  example2: '20231027_140213.bag'
  example3: '20231027_140520.bag'	
  example4: '20231027_140554.bag'
  example5: '20231027_140653.bag'
  example6: '20231027_140747.bag'
  example7: '20231027_140829.bag'
  example8: '20231027_140914.bag'
  example9: '20231027_140948.bag'
  example10: '20231124_163447.bag'
  example11: '20231124_164148.bag'
  example12: '20231124_164709.bag'
  example13: '20231201_152420.bag'

processing:
  enable_proc: True
  clip_limit: 4
  clip_replace: 153
  img_height: 480
  img_width: 640

tracker:
  type: 'CSRT'
  bbox_height: 150
  bbox_width: 200
  bbox_qmin: 15
  distance_trigger: 0.75

runtime: 
  display_window: True
  print_distance: False
  print_coord: False
  write_output: False
  output_root: '/home/fohara/Workspace/adapt-patient-tracker/logs/CSRT_MIN/'
  output_tag: 'TRACKER_CSRT'
